// resources/js/Pages/Admin/Modules/Index.vue
<template>
  <Layout>
    <div class="bg-white shadow rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <!-- Flash Messages -->
        <div v-if="$page.props.flash?.success" class="mb-4 bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
          {{ $page.props.flash.success }}
        </div>
        <div v-if="$page.props.flash?.error" class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {{ $page.props.flash.error }}
        </div>
        <div v-if="$page.props.errors?.upload" class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {{ $page.props.errors.upload }}
        </div>

        <div class="flex justify-between items-center mb-6">
          <h2 class="text-lg font-medium text-gray-900">Module Management</h2>
          <div class="flex space-x-3">
            <button
              @click="showUploadForm = !showUploadForm"
              class="bg-green-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-green-700"
            >
              Upload Module
            </button>
            <button
              @click="refreshModules"
              class="bg-indigo-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-indigo-700"
            >
              Refresh
            </button>
          </div>
        </div>

        <!-- Upload Form -->
        <div v-if="showUploadForm" class="bg-gray-50 p-6 rounded-lg mb-6">
          <h3 class="text-lg font-medium text-gray-900 mb-4">Upload Module ZIP</h3>
          <form @submit.prevent="uploadModule" enctype="multipart/form-data">
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2">
              <div>
                <label for="module_zip" class="block text-sm font-medium text-gray-700">
                  Module ZIP File
                </label>
                <input
                  id="module_zip"
                  ref="fileInput"
                  type="file"
                  accept=".zip"
                  required
                  class="mt-1 block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-indigo-50 file:text-indigo-700 hover:file:bg-indigo-100"
                />
              </div>
              <div>
                <label for="module_name" class="block text-sm font-medium text-gray-700">
                  Module Name (Optional)
                </label>
                <input
                  id="module_name"
                  v-model="uploadForm.module_name"
                  type="text"
                  placeholder="Leave empty to use name from ZIP"
                  class="mt-1 shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md"
                />
              </div>
            </div>
            <div class="mt-4 flex justify-end space-x-3">
              <button
                type="button"
                @click="showUploadForm = false"
                class="bg-gray-300 text-gray-700 px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-400"
              >
                Cancel
              </button>
              <button
                type="submit"
                :disabled="uploading"
                class="bg-green-600 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-green-700 disabled:opacity-50"
              >
                {{ uploading ? 'Uploading...' : 'Upload Module' }}
              </button>
            </div>
          </form>
        </div>

        <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg">
          <table class="min-w-full divide-y divide-gray-300">
            <thead class="bg-gray-50">
              <tr>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Module
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Version
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Status
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Dependencies
                </th>
                <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Actions
                </th>
              </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
              <tr v-for="(module, name) in modules" :key="name">
                <td class="px-6 py-4 whitespace-nowrap">
                  <div>
                    <div class="text-sm font-medium text-gray-900">{{ module.name }}</div>
                    <div class="text-sm text-gray-500">{{ module.description }}</div>
                  </div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                  {{ module.version }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span
                    :class="[
                      'inline-flex px-2 py-1 text-xs font-semibold rounded-full',
                      module.enabled
                        ? 'bg-green-100 text-green-800'
                        : 'bg-red-100 text-red-800'
                    ]"
                  >
                    {{ module.enabled ? 'Enabled' : 'Disabled' }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  <span v-if="module.dependencies && module.dependencies.length > 0">
                    {{ module.dependencies.join(', ') }}
                  </span>
                  <span v-else class="text-gray-400">None</span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <div class="flex space-x-2">
                    <button
                      v-if="module.enabled"
                      @click="disableModule(name)"
                      :disabled="processing"
                      class="text-red-600 hover:text-red-900 disabled:opacity-50"
                    >
                      Disable
                    </button>
                    <button
                      v-else
                      @click="enableModule(name)"
                      :disabled="processing"
                      class="text-indigo-600 hover:text-indigo-900 disabled:opacity-50"
                    >
                      Enable
                    </button>
                    <button
                      @click="downloadModule(name)"
                      :disabled="processing"
                      class="text-blue-600 hover:text-blue-900 disabled:opacity-50"
                    >
                      Download
                    </button>
                    <button
                      @click="uninstallModule(name)"
                      :disabled="processing"
                      class="text-red-600 hover:text-red-900 disabled:opacity-50"
                    >
                      Uninstall
                    </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </Layout>
</template>

<script setup>
import { ref } from 'vue'
import { router } from '@inertiajs/vue3'
import Layout from '../Layout.vue'

const props = defineProps({
  modules: {
    type: Object,
    required: true
  }
})

const processing = ref(false)
const uploading = ref(false)
const showUploadForm = ref(false)
const fileInput = ref(null)
const uploadForm = ref({
  module_name: ''
})

const enableModule = (name) => {
  processing.value = true
  router.post(route('admin.modules.enable'), { name }, {
    onFinish: () => processing.value = false
  })
}

const disableModule = (name) => {
  processing.value = true
  router.post(route('admin.modules.disable'), { name }, {
    onFinish: () => processing.value = false
  })
}

const uploadModule = () => {
  const fileElement = fileInput.value
  if (!fileElement.files[0]) {
    alert('Please select a ZIP file')
    return
  }

  uploading.value = true
  
  router.post(route('admin.modules.upload'), {
    module_zip: fileElement.files[0],
    module_name: uploadForm.value.module_name || null
  }, {
    forceFormData: true,
    onFinish: () => {
      uploading.value = false
    },
    onSuccess: () => {
      showUploadForm.value = false
      uploadForm.value.module_name = ''
      if (fileElement) {
        fileElement.value = ''
      }
    },
    onError: (errors) => {
      console.error('Upload errors:', errors)
    }
  })
}

const uninstallModule = (name) => {
  if (confirm(`Are you sure you want to uninstall module '${name}'? This action cannot be undone.`)) {
    processing.value = true
    router.post(route('admin.modules.uninstall'), { name }, {
      onFinish: () => processing.value = false
    })
  }
}

const downloadModule = (name) => {
  window.location.href = route('admin.modules.download', name)
}

const refreshModules = () => {
  router.reload()
}
</script>

// resources/js/Pages/Admin/Modules/Index.jsx
import React, { useState } from 'react';
import { Head, router, useForm } from '@inertiajs/react';
import AdminLayout from '../Layout';

export default function ModulesIndex({ modules }) {
    const [showUploadModal, setShowUploadModal] = useState(false);
    const { data, setData, post, processing, errors, reset } = useForm({
        module_zip: null,
        module_name: '',
    });

    const handleSubmit = (e) => {
        e.preventDefault();
        post('/admin/modules/upload', {
            onSuccess: () => {
                reset();
                setShowUploadModal(false);
            },
        });
    };

    const handleAction = (action, moduleName) => {
        if (action === 'uninstall') {
            if (!confirm(`Are you sure you want to uninstall ${moduleName}?`)) {
                return;
            }
        }
        
        router.post(`/admin/modules/${action}`, { name: moduleName });
    };

    return (
        <AdminLayout>
            <Head title="Modules" />
            
            <div className="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div className="p-6 bg-white border-b border-gray-200">
                    <div className="flex justify-between items-center mb-6">
                        <h2 className="text-2xl font-bold">Modules</h2>
                        <button
                            onClick={() => setShowUploadModal(true)}
                            className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md"
                        >
                            Upload Module
                        </button>
                    </div>

                    {modules && modules.length > 0 ? (
                        <div className="space-y-4">
                            {modules.map((module) => (
                                <div key={module.name} className="border border-gray-200 rounded-lg p-6">
                                    <div className="flex items-start justify-between">
                                        <div className="flex-1">
                                            <h3 className="text-lg font-semibold">{module.name}</h3>
                                            <p className="text-gray-600 mt-1">{module.description || 'No description'}</p>
                                            <div className="mt-2 flex items-center space-x-4 text-sm text-gray-500">
                                                <span>Version: {module.version || 'N/A'}</span>
                                                {module.author && <span>Author: {module.author}</span>}
                                            </div>
                                        </div>
                                        
                                        <div className="flex items-center space-x-2">
                                            <span className={`px-3 py-1 text-sm rounded-full ${
                                                module.enabled 
                                                    ? 'bg-green-100 text-green-800' 
                                                    : 'bg-gray-100 text-gray-800'
                                            }`}>
                                                {module.enabled ? 'Enabled' : 'Disabled'}
                                            </span>
                                            
                                            <button
                                                onClick={() => handleAction(module.enabled ? 'disable' : 'enable', module.name)}
                                                className={`px-3 py-1 text-sm rounded ${
                                                    module.enabled
                                                        ? 'bg-yellow-100 text-yellow-800 hover:bg-yellow-200'
                                                        : 'bg-green-100 text-green-800 hover:bg-green-200'
                                                }`}
                                            >
                                                {module.enabled ? 'Disable' : 'Enable'}
                                            </button>
                                            
                                            <a
                                                href={`/admin/modules/download/${module.name}`}
                                                className="px-3 py-1 text-sm rounded bg-blue-100 text-blue-800 hover:bg-blue-200"
                                            >
                                                Download
                                            </a>
                                            
                                            <button
                                                onClick={() => handleAction('uninstall', module.name)}
                                                className="px-3 py-1 text-sm rounded bg-red-100 text-red-800 hover:bg-red-200"
                                            >
                                                Uninstall
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <div className="text-center py-12 text-gray-500">
                            <p>No modules installed yet.</p>
                            <p className="mt-2">Upload a module to get started.</p>
                        </div>
                    )}
                </div>
            </div>

            {/* Upload Modal */}
            {showUploadModal && (
                <div className="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full z-50">
                    <div className="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
                        <div className="flex justify-between items-center mb-4">
                            <h3 className="text-lg font-semibold">Upload Module</h3>
                            <button
                                onClick={() => setShowUploadModal(false)}
                                className="text-gray-400 hover:text-gray-600"
                            >
                                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>
                        
                        <form onSubmit={handleSubmit}>
                            <div className="mb-4">
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Module ZIP File
                                </label>
                                <input
                                    type="file"
                                    accept=".zip"
                                    onChange={(e) => setData('module_zip', e.target.files[0])}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                                    required
                                />
                                {errors.module_zip && (
                                    <p className="mt-1 text-sm text-red-600">{errors.module_zip}</p>
                                )}
                            </div>
                            
                            <div className="mb-4">
                                <label className="block text-sm font-medium text-gray-700 mb-2">
                                    Module Name (Optional)
                                </label>
                                <input
                                    type="text"
                                    value={data.module_name}
                                    onChange={(e) => setData('module_name', e.target.value)}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500"
                                    placeholder="Leave empty to auto-detect"
                                />
                            </div>
                            
                            <div className="flex justify-end space-x-2">
                                <button
                                    type="button"
                                    onClick={() => setShowUploadModal(false)}
                                    className="px-4 py-2 bg-gray-200 text-gray-800 rounded-md hover:bg-gray-300"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    disabled={processing}
                                    className="px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700 disabled:opacity-50"
                                >
                                    {processing ? 'Uploading...' : 'Upload'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </AdminLayout>
    );
}
