// resources/js/Pages/Admin/Layout.jsx
import React from 'react';
import { Link, usePage } from '@inertiajs/react';

export default function AdminLayout({ children }) {
    const { url } = usePage();
    const { flash } = usePage().props;

    const isActive = (path) => {
        return url.startsWith(path);
    };

    return (
        <div className="min-h-screen bg-gray-100">
            {/* Navigation */}
            <nav className="bg-white border-b border-gray-200">
                <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="flex justify-between h-16">
                        <div className="flex">
                            <div className="flex-shrink-0 flex items-center">
                                <h1 className="text-xl font-bold">Admin Panel</h1>
                            </div>
                            <div className="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                                <Link
                                    href="/admin"
                                    className={`inline-flex items-center px-1 pt-1 border-b-2 ${
                                        isActive('/admin') && url === '/admin'
                                            ? 'border-indigo-500'
                                            : 'border-transparent'
                                    } text-sm font-medium`}
                                >
                                    Dashboard
                                </Link>
                                <Link
                                    href="/admin/modules"
                                    className={`inline-flex items-center px-1 pt-1 border-b-2 ${
                                        isActive('/admin/modules')
                                            ? 'border-indigo-500'
                                            : 'border-transparent'
                                    } text-sm font-medium`}
                                >
                                    Modules
                                </Link>
                                <Link
                                    href="/admin/settings"
                                    className={`inline-flex items-center px-1 pt-1 border-b-2 ${
                                        isActive('/admin/settings')
                                            ? 'border-indigo-500'
                                            : 'border-transparent'
                                    } text-sm font-medium`}
                                >
                                    Settings
                                </Link>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>

            {/* Page Content */}
            <main className="py-12">
                <div className="max-w-7xl mx-auto sm:px-6 lg:px-8">
                    {/* Flash Messages */}
                    {flash?.success && (
                        <div className="mb-4 bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
                            {flash.success}
                        </div>
                    )}

                    {flash?.error && (
                        <div className="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
                            {flash.error}
                        </div>
                    )}

                    {children}
                </div>
            </main>
        </div>
    );
}

// resources/js/Pages/Admin/Layout.vue
<template>
  <div class="min-h-screen bg-gray-100">
    <!-- Navigation -->
    <nav class="bg-white shadow-sm">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
          <div class="flex">
            <div class="flex-shrink-0 flex items-center">
              <h1 class="text-xl font-bold text-gray-900">Module Manager</h1>
            </div>
            <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
              <a
                :href="route('admin.dashboard')"
                :class="[
                  'inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium',
                  $page.component === 'Admin/Dashboard'
                    ? 'border-indigo-500 text-gray-900'
                    : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'
                ]"
              >
                Dashboard
              </a>
              <a
                :href="route('admin.modules.index')"
                :class="[
                  'inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium',
                  $page.component.startsWith('Admin/Modules')
                    ? 'border-indigo-500 text-gray-900'
                    : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'
                ]"
              >
                Modules
              </a>
              <a
                :href="route('admin.settings.index')"
                :class="[
                  'inline-flex items-center px-1 pt-1 border-b-2 text-sm font-medium',
                  $page.component.startsWith('Admin/Settings')
                    ? 'border-indigo-500 text-gray-900'
                    : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'
                ]"
              >
                Settings
              </a>
            </div>
          </div>
          <div class="flex items-center">
            <span class="text-sm text-gray-500">{{ $page.props.auth?.user?.name || 'Admin' }}</span>
          </div>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <main class="py-10">
      <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
        <!-- Flash Messages -->
        <div v-if="$page.props.flash?.success" class="mb-4 bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded">
          {{ $page.props.flash.success }}
        </div>
        <div v-if="$page.props.flash?.error" class="mb-4 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          {{ $page.props.flash.error }}
        </div>

        <slot />
      </div>
    </main>
  </div>
</template>

<script setup>
// No props needed, using slots
</script>
